build:
	docker-compose build
stop:
	docker-compose stop
down:
	docker-compose down
up:
	docker-compose down
	docker-compose up --remove-orphans
service:
	docker-compose up --d
term:
	docker-compose exec multicol_slam bash

